version: '2'
services:
  db:
    container_name: 'db'
    image: 'db'
    build: './db'
    depends_on:
      - consul
  web:
    container_name: 'web'
    image: 'web'
    build: './web'
    ports:
      - "8080:8080"
    depends_on:
      - registrator
  consul:
    container_name: consul
    command: "-node myconsul -bootstrap -data-dir=/consul/data/"
    image: gliderlabs/consul-server
  registrator:
    command: "-internal consul://consul:8500"
    image: gliderlabs/registrator:latest
    container_name: 'registrator'
    volumes:
     - "/var/run/docker.sock:/tmp/docker.sock"
    depends_on:
     - consul
